name: Build APK with Buildozer (Autogen Spec)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip git openjdk-17-jdk \
            autoconf automake build-essential libtool pkg-config \
            libffi-dev libssl-dev libsqlite3-dev libjpeg-dev \
            zlib1g-dev libpng-dev libfreetype6-dev libgl1-mesa-dev \
            libgles2-mesa-dev xclip xsel

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Create buildozer.spec if missing
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "[app]" > buildozer.spec
            echo "title = FaceRecognitionApp" >> buildozer.spec
            echo "package.name = facerecognitionapp" >> buildozer.spec
            echo "package.domain = org.apurv" >> buildozer.spec
            echo "source.dir = ." >> buildozer.spec
            echo "source.include_exts = py,png,jpg,kv,atlas" >> buildozer.spec
            echo "version = 1.0" >> buildozer.spec
            echo "requirements = python3,kivy,opencv-python,numpy,requests" >> buildozer.spec
            echo "orientation = portrait" >> buildozer.spec
            echo "osx.kivy_version = 2.1.0" >> buildozer.spec
            echo "android.archs = armeabi-v7a, arm64-v8a" >> buildozer.spec
            echo "android.ndk_api = 21" >> buildozer.spec
            echo "android.api = 31" >> buildozer.spec
          fi

      - name: Initialize buildozer
        run: buildozer android clean

      - name: Build the APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: facerecognitionapp-debug.apk
          path: bin/*.apk
