name: Build APK with Buildozer (Autogen Spec)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip cython3 git zip unzip openjdk-17-jdk wget autoconf libtool pkg-config
          python3 -m pip install --upgrade pip
          pip install cython buildozer

      - name: Setup Android SDK Tools
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
          cd $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O sdk.zip
          unzip sdk.zip -d temp
          mkdir -p latest
          mv temp/cmdline-tools/* latest/
          chmod +x latest/bin/sdkmanager
          yes | ./latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk "platforms;android-33" "platform-tools" "build-tools;34.0.0"

      - name: Manually install Apache Ant
        run: |
          mkdir -p $HOME/.buildozer/android/platform/apache-ant-1.9.4
          cd $HOME/.buildozer/android/platform
          wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.gz
          tar -xzf apache-ant-1.9.4-bin.tar.gz
          mv apache-ant-1.9.4 apache-ant-1.9.4-bin

      - name: Set Buildozer SDK & NDK paths manually
        run: |
          mkdir -p $HOME/.buildozer
          echo "[buildozer]" > $HOME/.buildozer/global.ini
          echo "android.sdk_path = $HOME/.buildozer/android/platform/android-sdk" >> $HOME/.buildozer/global.ini
          echo "android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b" >> $HOME/.buildozer/global.ini
          echo "android.ant_path = $HOME/.buildozer/android/platform/apache-ant-1.9.4-bin" >> $HOME/.buildozer/global.ini
          echo "android.accept_sdk_license = true" >> $HOME/.buildozer/global.ini
          echo "p4a.branch = master" >> $HOME/.buildozer/global.ini
          echo "p4a.bootstrap = sdl2" >> $HOME/.buildozer/global.ini

          # Fix legacy sdkmanager path issue
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
          ln -s $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

      - name: Generate buildozer.spec
        run: |
          buildozer init
          sed -i "s/^title = .*/title = FaceRecognitionApp/" buildozer.spec
          sed -i "s/^package.name = .*/package.name = facerecognitionapp/" buildozer.spec
          sed -i "s/^package.domain = .*/package.domain = org.example/" buildozer.spec
          sed -i "s/^source.dir = .*/source.dir = ./" buildozer.spec
          sed -i "s/^source.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas,json,xml/" buildozer.spec
          sed -i "s/^requirements = .*/requirements = python3,kivy,opencv-python,numpy,requests/" buildozer.spec
          sed -i "s/^android.permissions = .*/android.permissions = CAMERA,INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE/" buildozer.spec
          sed -i "s/^android.api = .*/android.api = 33/" buildozer.spec
          sed -i "s/^android.minapi = .*/android.minapi = 24/" buildozer.spec
          sed -i "s/^android.ndk = .*/android.ndk = 25b/" buildozer.spec
          sed -i "s/^android.archs = .*/android.archs = arm64-v8a,armeabi-v7a/" buildozer.spec

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: facialrecognition-debug-apk
          path: bin/*.apk
