name: Build APK with Buildozer (Autogen Spec)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev libffi-dev python3-dev python3-pip git zip unzip openjdk-17-jdk autoconf automake libtool pkg-config zlib1g-dev libncurses5 libncurses5-dev libncursesw5 libstdc++6
          pip install --upgrade pip setuptools cython virtualenv
          pip install buildozer

      - name: Create buildozer.spec if missing
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: bin/*.apk
