name: Build APK with Buildozer (Autogen Spec)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-17-jdk \
            zlib1g-dev libffi-dev libssl-dev \
            libsqlite3-dev libjpeg-dev libpng-dev \
            pkg-config git python3-pip python3-setuptools \
            autoconf automake build-essential
          pip install --upgrade pip Cython virtualenv
          pip install buildozer

      - name: Create buildozer.spec if not exists
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "[app]" > buildozer.spec
            echo "title = FaceRecognitionApp" >> buildozer.spec
            echo "package.name = facerecognitionapp" >> buildozer.spec
            echo "package.domain = org.example" >> buildozer.spec
            echo "source.dir = ." >> buildozer.spec
            echo "source.include_exts = py,png,jpg,kv,atlas" >> buildozer.spec
            echo "version = 0.1" >> buildozer.spec
            echo "requirements = python3,kivy,opencv-python,numpy,requests" >> buildozer.spec
            echo "orientation = portrait" >> buildozer.spec
            echo "osx.kivy_version = 2.1.0" >> buildozer.spec
            echo "android.arch = arm64-v8a, armeabi-v7a" >> buildozer.spec
          fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/*.apk
