name: Build APK with Buildozer (Autogen Spec)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk git wget autoconf libtool libffi-dev build-essential curl
          python3 -m pip install --upgrade pip
          pip install --upgrade buildozer cython

      - name: Download Android Command-line Tools
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          mkdir -p android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mv cmdline-tools android-sdk/cmdline-tools/latest

      - name: Set environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          echo "PATH=$HOME/.buildozer/android/platform/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Install SDK packages
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;21.4.7075529"

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/^#\(android.api\s*=\).*/\1 31/' buildozer.spec
          sed -i 's/^#\(android.minapi\s*=\).*/\1 21/' buildozer.spec
          sed -i 's/^#\(android.ndk\s*=\).*/\1 21.4.7075529/' buildozer.spec
          sed -i 's/^#\(requirements\s*=\).*/\1 python3,kivy,opencv-python,numpy,requests/' buildozer.spec
          sed -i 's/^#\(android.arch\s*=\).*/\1 arm64-v8a,armeabi-v7a/' buildozer.spec
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
